== Hola

image::https://www.plantuml.com/plantuml/png/hLDDRzGm4BtdLunwWaFx0wfgrLKf7mTwg0GNr8CtdcojEfvWZu4LslzEc6pYJB822N7qy_Fu-RtdsyGcScvzrPdwnUmHBjvGQrouW9yLm0Hkz_k8UyEOXWs0BziJyjRKJF7mfD5XMNlA5aRiCp56mGCnmewOgGLgpX00xfwnVe5lnZlh-00xR2WYy3C2THWDEmeZaxAtq99rpK486BW_yljinYGa35RkhCweUY1sZVkpCCK1aELmLyIKFVTSBKtV2d2Sc_c8NxEBnSfNh-6TOVnk3alcHxBe9yVlvLrF0sdI1fUNct9Umt92K1sMR4xCQwWZ6iR5QHrBpxgvUTXibYHjaUA9cHuRiMUXG5xqdhmLtwPwWSKEWyLGEqp01BlilArcNXwhghIoywuMlnTrlV_HKL86VqfOcxIAuaDWZAAe5BjWinAF0yIBDLmA8lFBYDwZaQFngwlDAfNhwRc5k8mg9rpl5t4w0Drc_OJ_-ybAG4jnsgA_w_k7pwRhKStIRQ9PLECH4qzHtr7WIDxZAUgoxfKNxQlQRAtf66UT4M2S8elJ2FMpZzKj1fjR_mi0[]

.Plantuml
[%collapsible]
====

[plantuml, "c4-context"]
....
@startuml
package "Domain" {
  package "Aggregates" {
    [AgregateFactory]
    [Agregate]
    cloud AgregateVoter
    note bottom of AgregateVoter
      Check validity before the operation
      Could modify the entity values
    end note

    cloud AgregateNotifier
    note bottom of AgregateNotifier
      Notify the result of the operation
    end note
  }
  package "Requires" {
    () Gateway
  }
  package "Model" {
    [Entity]
  }
  Agregate --> Gateway
  Agregate --> Entity
  AgregateFactory --> Agregate : create
  Agregate --> AgregateVoter : <<N>>
  Agregate --> AgregateNotifier : <<N>>
  note left of AgregateFactory
    Hold the Aggregate dependencies to build
  end note
}

package "Aplication" {
  package "Exposes" {
    () Usecase
  }
  package "Interactors" {
    [Interactor]
    cloud UsecaseVoter
    cloud UsecaseNotifier
  }
  Interactor -- Usecase
  Interactor ..> AgregateFactory : build
  Interactor --> Agregate : use
  Interactor --> UsecaseVoter : <<N>>
  note bottom of UsecaseVoter
     Check validity before the operation
      Could modify the entity values
  end note
  Interactor --> UsecaseNotifier : <<N>>
  note bottom of UsecaseNotifier
      Notify the result of the operation
  end note
}


package "Infra" {
  package "Rest" {
    [Controller]
    Controller ----> Usecase
  }
  package "Adapters" {
    [Adapter]
    Adapter ---- Gateway
  }
}
@enduml
....

====
